### ISSUE TITLE
Request file - india_villages_master_2011.gpkg

### ISSUE THREAD

**Issue by HariprasadManimozhi** [samashti/KGIS#1]
Dear Samashti,
I came across your blog dealing with geo-spatial analysis.
I'm also working on a similar kind of project to visualize all villages of India from census data.
If you don't mind, Request you kindly share the entire data file of villages in geopackage format.
Else, you can share the way of converting the shapefile into geopackage format.

Looking forward to your response. Thanks.

**Comment by samashti** [comment]
Hey, you can find the village boundaries for 2011 [here](https://github.com/justinelliotmeyers/official_india_2011_village_boundary_polygons) and also [here](https://projects.datameet.org/indian_village_boundaries/). The second link does not have for all the states. 
Also, the first link has files separate for each state. You will have to merge them together. Once you have the shapefile, you can convert them to gpkg format using the following command on terminal if you have GDAL installed.

`$ ogr2ogr -f GPKG filename.gpkg abc.shp` 

or you can use QGIS, GeoPandas or other GIS software to convert a shapefile into Geopackage.

**Comment by HariprasadManimozhi** [comment]
> Hey, you can find the village boundaries for 2011 [here](https://github.com/justinelliotmeyers/official_india_2011_village_boundary_polygons) and also [here](https://projects.datameet.org/indian_village_boundaries/). The second link does not have for all the states. Also, the first link has files separate for each state. You will have to merge them together. Once you have the shapefile, you can convert them to gpkg format using the following command on terminal if you have GDAL installed.
> 
> `$ ogr2ogr -f GPKG filename.gpkg abc.shp`
> 
> or you can use QGIS, GeoPandas or other GIS software to convert a shapefile into Geopackage.

Thanks for sharing the information. This would be really helpful.
